### ISSUE TITLE
List of commands and params

### ISSUE THREAD

**Issue by BeardAndHarleyWojciech** [marklagendijk/obs-scene-execute-command-script#10]
Hi,
In your README you provided an example of a request to load a preset.
Is there a list of commands and example params (especially interesting for Lumens cameras) somewhere?
I am especially interested in moving to the left and right, top to bottom, etc.
Thank you!

Regards,
Wojciech

**Comment by marklagendijk** [comment]
No, that does not exist.

You have two options:
- If the camera supports ONVIF you could use [onvif-ptz-cli](https://github.com/marklagendijk/node-onvif-ptz-cli)
- You can use the web application of your camera to execute the commands you are looking for, and replicate those requests using a tool like curl.
