### ISSUE TITLE
Feature Request: Run Silently

### ISSUE THREAD

**Issue by Emmett-Boedeker** [marklagendijk/obs-scene-execute-command-script#5]
I love the functionality of this script, but I'd love it even more if it ran the command without popping up a CMD window. Is that a possibility?

**Comment by marklagendijk** [comment]
Unfortunately this cannot be fixed, because this is a limitation of the Lua script engine.

**Comment by Barabba11** [comment]
this method is not the best, unfortunately. I don't have the problem of te dos box becuae I?m running projector always on top, but when the dos box starts it frozen the streams.. I would like to have something lighter if possible. I'm going to have a look on your sources )
