### ISSUE TITLE
Scene Execute Command 1.0.1 - Tilt Movement

### ISSUE THREAD

**Issue by mulviz-rj** [marklagendijk/obs-scene-execute-command-script#6]
Hello, I ask for help with the command execution in obs-scene-execute-command-script, I have a generic camera that has the Tilt function, I access it via RTSP, with this line rtsp://admin:Password@192.168.1.90 /11 and it works, when I put the script to work I have no answer, can you help me I tried 

curl http://192.168.1.90/command/presetposition.cgi?PresetCall=SCENE_VALUE --digest -u admin:Password 

But I don't have successful, has anyone had success with something similar?

I accessed the camera by ip and in the browser I managed to make the camera move to the preset positions, is it possible to adapt to run this in the script?

http://192.168.1.90/web/cgi-bin/hi3510/param.cgi?cmd=preset&-act=goto&-status=1&-number=2

Is it possible to receive a confirmation that the script is communicating with the camera?

**Comment by marklagendijk** [comment]
First you need to get it working directly from Command Prompt (Windows) or Bash (Linux).

So you would try something like:
```
curl http://192.168.1.90/web/cgi-bin/hi3510/param.cgi?cmd=preset&-act=goto&-status=1&-number=2 --digest -u admin:Password
```
Only move to trying it from the OBS script when you have this working.
When you have it working you can adjust the command to parameterize the preset number, by replacing it with SCENE_VALUE. My guess would be that in your case this is the `-number` param. So you would get:
```
curl http://192.168.1.90/web/cgi-bin/hi3510/param.cgi?cmd=preset&-act=goto&-status=1&-number=SCENE_VALUE --digest -u admin:Password
```
